#!/usr/bin/env bash
# Cheking for command line arguments

if [ $# -lt 4 ]
then
	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

# disabbling strict host key checking

scp -o "strictHostkeyChecking=no" -i "$path_to_shh_key" "$path_to_file" "$username@ip:~/"


# checking if the transfer was succesful
if [ $? -eq 0]
then 
	echo "FILE WAS TRANSFERED SUCCESFULLY"
else 
	echo "FILE TRANSFER FAILED"
fi 
